### ISSUE TITLE
Errors out with sass.compile()

### ISSUE THREAD

**Issue by bronzehedwick** [loilo/node-sass-yaml-importer#64]
Hello!

The plugin says it is compatible with Dart SASS, which it is, but seemingly only the legacy `render`/`renderSync` API. When I tried using the supported `compile` method, Dart SASS returned this error:

```
Error: An importer must have either canonicalize and load methods, or a findFileUrl method.
```

Here is my implementation code:

```js
const sass = require('sass');
const yamlImporter = require('node-sass-yaml-importer');

const result = sass.compile('my-styles.scss', {
  style: 'compressed',
  importers: [yamlImporter]
});
```

Thanks!

**Comment by loilo** [comment]
Hey @bronzehedwick,

this is right, it only offers an importer for the legacy API. Since I mostly just adjusted [node-sass-json-importer](https://www.npmjs.com/package/node-sass-json-importer) at the time, I'm not intimately familiar with Sass' new JavaScript APIs and I don't have a lot of time to get started with those.

Feel free to create a PR for the new API, would be happy to add it.

**Comment by loilo** [comment]
Okay, I have taken quite a deep dive into the new API. Unfortunately, I cannot implement this until sass/sass#3247 is resolved because resolution of relative files currently does not work properly with importers.

**Comment by loilo** [comment]
@bronzehedwick Although you're possibly no longer affected by this issue: This has been fixed in v8, there is now an importer version for the legacy as well as the modern Sass JavaScript API.
